-- use this file to map the AP item ids to your items
-- first value is the code of the target item and the second is the item type override. The third value is an optional increment multiplier for consumables. (feel free to expand the table with any other values you might need (i.e. special initial values, etc.)!)
-- here are the SM items as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/item_mapping.lua
BASE_ITEM_ID = 0
ITEM_MAPPING = {
	-- Relics
	[BASE_ITEM_ID + 112] = { { "slide" } },
	[BASE_ITEM_ID + 113] = { { "djump" } },
	[BASE_ITEM_ID + 114] = { { "dive" } },
	[BASE_ITEM_ID + 115] = { { "special" } },
	[BASE_ITEM_ID + 116] = { { "jewelbox" } },
	[BASE_ITEM_ID + 117] = { { "names" } },

	-- Villagers
	[BASE_ITEM_ID + 360] = { { "priest" } },
	[BASE_ITEM_ID + 361] = { { "merhcant" } },
	[BASE_ITEM_ID + 362] = { { "healer" } },
	[BASE_ITEM_ID + 363] = { { "jewelist" } },
	[BASE_ITEM_ID + 364] = { { "blacksmith" } },
	[BASE_ITEM_ID + 365] = { { "chef" } },
	[BASE_ITEM_ID + 366] = { { "reporter" } },
	[BASE_ITEM_ID + 367] = { { "musician" } },
	[BASE_ITEM_ID + 368] = { { "boy" } },
	[BASE_ITEM_ID + 369] = { { "girl" } },
	[BASE_ITEM_ID + 370] = { { "clothier" } },
	[BASE_ITEM_ID + 371] = { { "mom" } },
	[BASE_ITEM_ID + 372] = { { "grandma" } },

	-- Map
	[BASE_ITEM_ID + 377] = { { "training" } },
	[BASE_ITEM_ID + 378] = { { "ruvas" } },
	[BASE_ITEM_ID + 379] = { { "argila" } },
	[BASE_ITEM_ID + 380] = { { "kalidus", nil, 1 } },
	[BASE_ITEM_ID + 381] = { { "somnus" } },
	[BASE_ITEM_ID + 382] = { { "minera" } },
	[BASE_ITEM_ID + 383] = { { "lighthouse" } },
	[BASE_ITEM_ID + 384] = { { "tymeo" } },
	[BASE_ITEM_ID + 385] = { { "tristis" } },
	[BASE_ITEM_ID + 386] = { { "large" } },
	[BASE_ITEM_ID + 387] = { { "giants" } },
	[BASE_ITEM_ID + 387] = { { "mystery" } },
	[BASE_ITEM_ID + 388] = { { "misty" } },
	[BASE_ITEM_ID + 389] = { { "oblivion" } },
	[BASE_ITEM_ID + 390] = { { "skeleton" } },
	[BASE_ITEM_ID + 391] = { { "monastery" } },

	-- Arm Glyphs
	[BASE_ITEM_ID + 002] = { { "rapier1" } },
	[BASE_ITEM_ID + 003] = { { "rapier2" } },
	[BASE_ITEM_ID + 004] = { { "rapier3" } },
	[BASE_ITEM_ID + 005] = { { "sword1" } },
	[BASE_ITEM_ID + 006] = { { "sword2" } },
	[BASE_ITEM_ID + 007] = { { "sword3" } },
	[BASE_ITEM_ID + 008] = { { "lance1" } },
	[BASE_ITEM_ID + 009] = { { "lance2" } },
	[BASE_ITEM_ID + 010] = { { "lance3" } },
	[BASE_ITEM_ID + 011] = { { "hammer1" } },
	[BASE_ITEM_ID + 012] = { { "hammer2" } },
	[BASE_ITEM_ID + 013] = { { "hammer3" } },
	[BASE_ITEM_ID + 014] = { { "bow1" } },
	[BASE_ITEM_ID + 015] = { { "bow2" } },
	[BASE_ITEM_ID + 016] = { { "bow3" } },
	[BASE_ITEM_ID + 017] = { { "axe1" } },
	[BASE_ITEM_ID + 018] = { { "axe2" } },
	[BASE_ITEM_ID + 019] = { { "axe3" } },
	[BASE_ITEM_ID + 020] = { { "scythe1" } },
	[BASE_ITEM_ID + 021] = { { "scythe2" } },
	[BASE_ITEM_ID + 022] = { { "scythe3" } },
	[BASE_ITEM_ID + 023] = { { "knife1" } },
	[BASE_ITEM_ID + 024] = { { "knife2" } },
	[BASE_ITEM_ID + 025] = { { "knife3" } },
	[BASE_ITEM_ID + 026] = { { "shield1" } },
	[BASE_ITEM_ID + 027] = { { "shield2" } },
	[BASE_ITEM_ID + 028] = { { "shield3" } },
	[BASE_ITEM_ID + 029] = { { "fun" } },
	[BASE_ITEM_ID + 030] = { { "block" } },
	[BASE_ITEM_ID + 031] = { { "crystal" } },
	[BASE_ITEM_ID + 032] = { { "water" } },
	[BASE_ITEM_ID + 033] = { { "wind" } },
	[BASE_ITEM_ID + 034] = { { "fire1" } },
	[BASE_ITEM_ID + 035] = { { "fire2" } },
	[BASE_ITEM_ID + 036] = { { "rock1" } },
	[BASE_ITEM_ID + 037] = { { "rock2" } },
	[BASE_ITEM_ID + 038] = { { "electric1" } },
	[BASE_ITEM_ID + 039] = { { "electric2" } },
	[BASE_ITEM_ID + 040] = { { "light1" } },
	[BASE_ITEM_ID + 041] = { { "light2" } },
	[BASE_ITEM_ID + 042] = { { "dark1" } },
	[BASE_ITEM_ID + 043] = { { "dark2" } },
	[BASE_ITEM_ID + 044] = { { "morbius" } },
	[BASE_ITEM_ID + 045] = { { "beam" } },
	[BASE_ITEM_ID + 046] = { { "morbius" } },
	[BASE_ITEM_ID + 047] = { { "morbius" } },
	[BASE_ITEM_ID + 048] = { { "cerberus1" } },
	[BASE_ITEM_ID + 049] = { { "cerberus2" } },
	[BASE_ITEM_ID + 050] = { { "dominus1" } },
	[BASE_ITEM_ID + 051] = { { "dominus2" } },

	-- Back Glyphs
	[BASE_ITEM_ID + 052] = { { "magnet" } },
	[BASE_ITEM_ID + 053] = { { "wall" } },
	[BASE_ITEM_ID + 054] = { { "wings" } },
	[BASE_ITEM_ID + 055] = { { "fast" } },
	[BASE_ITEM_ID + 056] = { { "str" } },
	[BASE_ITEM_ID + 057] = { { "con" } },
	[BASE_ITEM_ID + 058] = { { "mnd" } },
	[BASE_ITEM_ID + 059] = { { "magnet" } },
	[BASE_ITEM_ID + 060] = { { "lck" } },
	[BASE_ITEM_ID + 061] = { { "all" } },
	[BASE_ITEM_ID + 062] = { { "cat" } },
	[BASE_ITEM_ID + 063] = { { "bat" } },
	[BASE_ITEM_ID + 064] = { { "bot" } },
	[BASE_ITEM_ID + 065] = { { "h" } },
	[BASE_ITEM_ID + 066] = { { "cerberus3" } },
	[BASE_ITEM_ID + 067] = { { "all" } },
	[BASE_ITEM_ID + 068] = { { "all" } },
	[BASE_ITEM_ID + 069] = { { "all" } },
	[BASE_ITEM_ID + 070] = { { "all" } },
	[BASE_ITEM_ID + 071] = { { "medusa" } },
	[BASE_ITEM_ID + 072] = { { "spider" } },
	[BASE_ITEM_ID + 073] = { { "all" } },
	[BASE_ITEM_ID + 074] = { { "dominus3" } },
	[BASE_ITEM_ID + 075] = { { "all" } },

	[BASE_ITEM_ID + 00001] = { { "progressive" } },
	[BASE_ITEM_ID + 00002] = { { "consumable" } },
	-- handle progressive_toggle as toggle, only changing it's active state
	[BASE_ITEM_ID + 00003] = { { "progressive_toggle", "toggle" } },
	-- multiple items on this id, add the consumable 3 times
	[BASE_ITEM_ID + 00004] = { { "toggle" }, { "consumable", nil, 3 } }
}
